baseURL = "https://guessthesc2pro.com/"
title = "Guess the SC2 Pro"
author = "tobijdc"
copyright = "Tobias Ibounig"
paginate = 10
languageCode = "en"
theme = "anubis"
enableRobotsTXT = true
enableEmoji = true

disqusShortname = ""
googleAnalytics = ""

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  style = "light-without-switcher"

  showReadingTime = false
  toc = false

  [params.header]
    logo = "logo.webp"

  [params.footer]
    since = 2024
    poweredby = false

[menu]
  [[menu.main]]
    identifier = "normal-mode"
    name = "Normal"
    pageRef = "/"
    weight = 20

  [[menu.main]]
    identifier = "hard"
    name = "Hard"
    pageRef = "/hard-mode"
    weight = 30

  [[menu.main]]
    identifier = "katowice"
    name = "Katowice"
    pageRef = "/katowice"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 50
