baseURL = "https://guessthesc2pro.com/"
title = "Guess the SC2 Pro"
author = "tobijdc"
copyright = "Tobias Ibounig"
pagination.pagerSize = 10
languageCode = "en"
theme = "anubis2"
enableRobotsTXT = true
enableEmoji = true

# Anubis2
rssAsSocialIcon = false
locale = "en-us"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  style = "light-without-switcher"

  showReadingTime = false

  [params.header]
    logo = "logo.webp"

  [params.footer]
    since = 2024
    poweredby = false

[menu]
  [[menu.main]]
    identifier = "normal-mode"
    name = "Normal"
    pageRef = "/"
    weight = 20

  [[menu.main]]
    identifier = "hard"
    name = "Hard"
    pageRef = "/hard-mode"
    weight = 30

  #[[menu.main]]
  #  identifier = "katowice"
  #  name = "Katowice"
  #  pageRef = "/katowice"
  #  weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 50

# Anubis2

[params.anubis2]
    tocWordCount = 0
    readNextPosts = 0
    enableMathGlobally = false # MathJax (default is false)
    enableCopyCodeButton = false
    enableReadMoreButton = false
    hideFooterAttribution = false # hide "Powered by Hugo, theme" in footer
    colorTheme = "auto"
    enableColorThemeSwitcher = true
    enableRssIcon = false
    enableSummary = false

    customCSS = ["custom-css/custom.css"]

    socialIcons = []
