on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 5'
#permissions:
#  contents: write
jobs:
  import_aligulac:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install postgres client
        run: sudo apt-get install -y postgresql-client
      - name: Postgres client version
        run: psql --version
      - name: Install yq
        run: sudo snap install yq --channel=v4/stable
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Aligulac dump
        run: wget -qO- http://static.aligulac.com/aligulac.sql.gz | gzip -d > aligulac.sql
      - name: Import Aligulac DB
        run: PGPASSWORD=postgres psql -h localhost -p 5432  -d postgres -U postgres -f aligulac.sql
      - name: Import GuessTheSC2Pro Fixes
        run: PGPASSWORD=postgres psql -h localhost -p 5432  -d postgres -U postgres -f db_import/data-fixup.sql
      - name: Export player data
        run: PGPASSWORD=postgres psql -h localhost -p 5432  -d postgres -U postgres -t --csv -f db_import/top500-earnings.sql > result.csv
      - name: Display CSV
        run: cat result.csv
      - name: Convert to JSON
        run: yq result.csv -p=csv -o=json > players.json
      - name: Display JSON
        run: cat players.json
      #- name: Commit changes
      #  run: |
      #    git config --global user.name 'GH Action Bot'
      #    git config --global user.email 'tobijdce@users.noreply.github.com'
      #    git add TODO
      #    git commit -m "Automated Player Update"
      #    git push
